### ISSUE TITLE
Following the example and in the fit function I got the error

### ISSUE THREAD

**Issue by flyree** [david-cortes/costsensitive#2]
Hi ,

I am following the example provided in the ipython notebook and when it calls the fit:
Traceback (most recent call last):
  File "multiclass.py", line 71, in <module>
    costsensitive_WAP.fit(X_train, C_train)
  File "/home/fang587/.local/lib/python2.7/site-packages/costsensitive/__init__.py", line 83, in fit
    self.classifiers[ix].fit(X_take, y_take, sample_weight=w_take)
  File "/home/fang587/.local/lib/python2.7/site-packages/sklearn/linear_model/logistic.py", line 1288, in fit
    accept_large_sparse=solver != 'liblinear')
  File "/home/fang587/.local/lib/python2.7/site-packages/sklearn/utils/validation.py", line 756, in check_X_y
    estimator=estimator)
  File "/home/fang587/.local/lib/python2.7/site-packages/sklearn/utils/validation.py", line 582, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 54)) while a minimum of 1 is required.

The shape of my X_train and C_train looks like this:
(522910, 54)
(522910, 7)

I have tested with different classifiers, with different inputs, I always get this error.

**Comment by david-cortes** [comment]
I'm unable to reproduce the error. Please provide more details:
* NumPy version
* SciPy version
* Scikit-learn version
* Operating system

Have you tried using Python 3? In case you're not using the latest NumPy, can you try upgrading?
